
import { Translations } from './types';

export const TRANSLATIONS: Record<'tr' | 'en', Translations> = {
  tr: {
    title: "Emel & Onur | Düğün RSVP",
    names: "Emel & Onur",
    date: "25 Temmuz 2026",
    welcomeHeader: "Merhaba",
    welcomeText: "Düğün web sitemize hoş geldiniz! Bu mutlu günümüzde yanımızda olmanızdan büyük sevinç duyacağız. Katılım durumunuzu aşağıdaki formdan bize iletebilirsiniz.",
    rsvpTitle: "LCV (RSVP)",
    firstNameLabel: "Adınız",
    lastNameLabel: "Soyadınız",
    firstNamePlaceholder: "Adınızı giriniz",
    lastNamePlaceholder: "Soyadınız giriniz",
    attendanceLabel: "Katılım Durumunuz",
    attendanceYes: "Memnuniyetle Katılıyorum",
    attendanceNo: "Maalesef Katılamıyorum",
    foodPreferenceLabel: "Yemek Tercihiniz",
    foodStandard: "Standart Menü",
    foodVeggie: "Vejetaryen",
    foodVegan: "Vegan",
    plusOneLabel: "Yanınızda misafir gelecek mi?",
    plusOneYes: "Evet",
    plusOneNo: "Hayır",
    plusOneGuestName: "Misafir Adı ve Soyadı",
    plusOneGuestNamePlaceholder: "Misafirinizin adını giriniz",
    plusOneGuestFood: "Misafir Yemek Tercihi",
    notesLabel: "Ek Notlar veya Alerjiler",
    notesPlaceholder: "Bilmemiz gereken başka bir detay var mı?",
    submitButton: "Cevabı Gönder",
    footerText: "Sevgilerle, Emel & Onur"
  },
  en: {
    title: "Emel & Onur | Wedding RSVP",
    names: "Emel & Onur",
    date: "July 25, 2026",
    welcomeHeader: "Hello",
    welcomeText: "Welcome to our wedding website! We are so excited to have you with us on this special day. Please let us know if you can attend using the form below.",
    rsvpTitle: "RSVP",
    firstNameLabel: "First Name",
    lastNameLabel: "Last Name",
    firstNamePlaceholder: "Enter your first name",
    lastNamePlaceholder: "Enter your last name",
    attendanceLabel: "Will you attend?",
    attendanceYes: "Joyfully Accept",
    attendanceNo: "Regretfully Decline",
    foodPreferenceLabel: "Your Meal Preference",
    foodStandard: "Standard Menu",
    foodVeggie: "Vegetarian",
    foodVegan: "Vegan",
    plusOneLabel: "Will you bring a guest?",
    plusOneYes: "Yes",
    plusOneNo: "No",
    plusOneGuestName: "Guest's Full Name",
    plusOneGuestNamePlaceholder: "Enter your guest's name",
    plusOneGuestFood: "Guest's Meal Preference",
    notesLabel: "Extra Notes or Allergies",
    notesPlaceholder: "Anything else we should know?",
    submitButton: "Send Response",
    footerText: "With love, Emel & Onur"
  }
};
