import { Translations, Language } from './types';

export const TRANSLATIONS: Record<Language, Translations> = {
  TR: {
    title: 'Emel & Onur',
    date: '25 TEMMUZ 2026',
    welcomeTitle: 'Merhaba',
    welcomeText: 'Düğün web sitemize hoş geldiniz! İsviçre\'deki bu mutlu günümüzde yanımızda olmanızdan büyük sevinç duyacağız. Katılım durumunuzu aşağıdaki formdan bize iletebilirsiniz.',
    rsvpTitle: 'LCV (RSVP)',
    locationTitle: 'Konumlar',
    venueZurichTitle: 'Nikah: Zürich Stadthaus',
    venueZurichAddress: 'Stadthausquai 17, 8001 Zürich',
    venueWinterthurTitle: 'Kutlama: Kulturhaus Villa Sträuli',
    venueWinterthurAddress: 'Museumstrasse 60, 8400 Winterthur',
    viewOnMaps: 'Haritada Görüntüle',
    attractionsTitle: 'Öneriler ve Gezilecek Yerler',
    zurichTitle: 'Zürih\'te Neler Yapılır?',
    zurichAttractions: [
      'Altstadt (Eski Şehir): Tarihi sokaklarda ve Limmat nehri kıyısında yürüyüş yapın.',
      'Zürichsee (Zürih Gölü): Göl kenarında bir yürüyüş veya tekne turu.',
      'Grossmünster & Fraumünster: Şehrin ikonik kiliseleri ve Marc Chagall camları.',
      'Bahnhofstrasse: Dünyaca ünlü alışveriş caddesi.'
    ],
    winterthurTitle: 'Winterthur\'da Neler Yapılır?',
    winterthurAttractions: [
      'Fotomuseum: Avrupa\'nın önde gelen fotoğraf müzelerinden biri.',
      'Altstadt Winterthur: İsviçre\'nin en büyük araç trafiğine kapalı eski şehir bölgesi.',
      'Technorama: İnteraktif bilim merkezi ve teknoloji müzesi.',
      'Rosengarten: Şehri tepeden gören muazzam bir gül bahçesi.'
    ],
    eatTitle: 'İsviçre Lezzetleri',
    firstName: 'Adınız',
    lastName: 'Soyadınız',
    participationStatus: 'Katılım Durumunuz',
    accept: 'Memnuniyetle Katılıyorum',
    decline: 'Maalesef Katılamıyorum',
    mealPreference: 'Yemek Tercihi',
    standardMenu: 'Standart Menü',
    vegetarian: 'Vejetaryen',
    vegan: 'Vegan',
    plusOneQuestion: 'Yanınızda misafir gelecek mi?',
    yes: 'Evet',
    no: 'Hayır',
    plusOneName: 'Misafir Adı ve Soyadı',
    plusOneMeal: 'Misafir Yemek Tercihi',
    notes: 'Ek Notlar veya Alerjiler',
    notesPlaceholder: 'Bilmemiz gereken başka bir detay var mı?',
    submitButton: 'Cevabı Gönder',
    footerText: 'Sevgilerle, Emel & Onur',
    namePlaceholder: 'Adınızı giriniz',
    lastNamePlaceholder: 'Soyadınızı giriniz',
    guestNamePlaceholder: 'Misafirinizin adını giriniz',
    menuLocation: 'Konum',
    menuAttractions: 'Gezilecek Yerler',
    menuRsvp: 'LCV',
    scheduleTitle: 'Program',
    arrivalTitle: 'Varış',
    arrivalText: 'Nikah 14:00\'de başlayacaktır. Tören için en geç 13:30\'da Stadthaus\'ta olmanızı öneririz.',
    ceremonyTitle: 'Nikah Töreni',
    celebrationTitle: 'Kutlama Daveti',
    transportTitle: 'Ulaşım Önerisi',
    transportText: 'Villa Sträuli’ye ulaşım için toplu taşıma en pratik seçenektir. Zürich şehir merkezinden (Zürich HB veya Stadelhofen) Winterthur’a giden trenlere binebilirsiniz. Ayrıca Zürich Havalimanı’ndan (Zürich Flughafen) direkt trenlerle yaklaşık 20-30 dakika içinde Winterthur’a ulaşmak mümkündür. Winterthur tren istasyonundan Villa Sträuli’ye ulaşmak için Bahnhof Oberwinterthur yönüne giden 10 numaralı otobüse binebilir ve “Bezirksgebäude” durağında inebilirsiniz ya da yaklaşık 10 dakikalık keyifli bir yürüyüş yapabilirsiniz.'
  },
  EN: {
    title: 'Emel & Onur',
    date: 'JULY 25, 2026',
    welcomeTitle: 'Welcome',
    welcomeText: 'Welcome to our wedding website! We would be delighted to have you with us on our special day in Switzerland. You can let us know your attendance status via the form below.',
    rsvpTitle: 'RSVP',
    locationTitle: 'Locations',
    venueZurichTitle: 'Ceremony: Zurich Stadthaus',
    venueZurichAddress: 'Stadthausquai 17, 8001 Zürich',
    venueWinterthurTitle: 'Celebration: Kulturhaus Villa Sträuli',
    venueWinterthurAddress: 'Museumstrasse 60, 8400 Winterthur',
    viewOnMaps: 'View on Maps',
    attractionsTitle: 'Attractions & Recommendations',
    zurichTitle: 'Things to do in Zurich',
    zurichAttractions: [
      'Altstadt (Old Town): Walk through the historic medieval streets and along the Limmat river.',
      'Zürichsee (Lake Zurich): A scenic walk or a relaxing boat tour.',
      'Grossmünster & Fraumünster: Iconic churches with Chagall windows.',
      'Bahnhofstrasse: World-famous shopping street.'
    ],
    winterthurTitle: 'Things to do in Winterthur',
    winterthurAttractions: [
      'Fotomuseum & Fotostiftung: Leading photography museums in Europe.',
      'Winterthur Altstadt: Switzerland\'s largest pedestrian old town.',
      'Technorama: Interactive science and technology museum.',
      'Rosengarten: Beautiful rose garden with a panoramic view of the city.'
    ],
    eatTitle: 'Swiss Delights',
    firstName: 'First Name',
    lastName: 'Last Name',
    participationStatus: 'Attendance Status',
    accept: 'Joyfully Accept',
    decline: 'Regretfully Decline',
    mealPreference: 'Meal Preference',
    standardMenu: 'Standard Menu',
    vegetarian: 'Vegetarian',
    vegan: 'Vegan',
    plusOneQuestion: 'Will you bring a plus-one?',
    yes: 'Yes',
    no: 'No',
    plusOneName: 'Plus-one Name & Surname',
    plusOneMeal: 'Plus-one Meal Preference',
    notes: 'Additional Notes or Allergies',
    notesPlaceholder: 'Any other details we should know?',
    submitButton: 'Submit Response',
    footerText: 'With Love, Emel & Onur',
    namePlaceholder: 'Enter your name',
    lastNamePlaceholder: 'Enter your last name',
    guestNamePlaceholder: 'Enter guest name',
    menuLocation: 'Location',
    menuAttractions: 'Attractions',
    menuRsvp: 'RSVP',
    scheduleTitle: 'Schedule',
    arrivalTitle: 'Arrival',
    arrivalText: 'The ceremony starts at 14:00. We suggest arriving at the Stadthaus by 13:30 to find your seats.',
    ceremonyTitle: 'Wedding Ceremony',
    celebrationTitle: 'Celebration Party',
    transportTitle: 'Transportation Advice',
    transportText: 'Public transportation is the most convenient way to reach Villa Sträuli. From Zurich city center (Zurich HB or Stadelhofen), you can take trains to Winterthur. There are also direct trains from Zurich Airport (Zurich Flughafen), and the journey to Winterthur takes about 20–30 minutes. From Winterthur train station, you can take bus line 10 in the direction of Bahnhof Oberwinterthur and get off at the “Bezirksgebäude” stop, or enjoy a pleasant walk of about 10 minutes.'
  }
};
